spec:
  template:
    projects:
      - git:
          remotes:
            origin: >-
              https://github.com/rclements-redhat/dayinthelife-serverless.git#
        name: International-Incorporated